name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # a cada 12h, no minuto 0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Snake GIF
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: eidisato
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
